create table users
(
    id integer primary key generated always as identity,
    role               varchar,
    status             varchar,

    user_name          varchar,
    password           varchar,

    gender             varchar,
    birth_date         date,
    email_address      varchar,


    full_name          varchar,
    contact_number     varchar
);


create table images
(
    id                  integer primary key generated always as identity,
    user_id             integer,
    status              varchar,

    short_description   varchar,
    long_description    varchar,
    created_at          timestamp default now(),

    orders              int default 0,
    rating              double precision default 0.0,
    price               double precision,
    url                 varchar,

    constraint fk_users
        foreign key(user_id)
            references users(id)
);


create table ratings
(
    id             integer primary key generated always as identity,
    user_id        integer,
    image_id       integer,

    rating         smallint check (rating between 1 and 5),
    review         varchar,
    status         varchar(10),
    created_at     timestamp default now(),

    constraint fk_users
        foreign key(user_id)
            references users(id),

    constraint fk_images
        foreign key(image_id)
            references images(id)
);


create table orders
(
    id                     integer primary key generated always as identity,
    user_id                integer,
    image_id               integer,

    status                 varchar(16),
    with_discount          boolean,
    amount                 double precision,
    created_at             timestamp default now(),

    constraint fk_users
        foreign key(user_id)
            references users(id),

    constraint fk_images
        foreign key(image_id)
            references images(id)
);


insert into users (role, status, user_name, password, gender, birth_date, email_address, full_name, contact_number)
values('admin', 'active', 'admin',   '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', 'female', '2004-01-30', 'admin@gmail.com', 'admin full name',  '70000000000');
insert into users (role, status, user_name, password, gender, birth_date, email_address, full_name, contact_number)
values('user', 'active', 'username', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', 'female', '2022-11-30', 'user@gmail.com',  'user full name',   '70000000000');


insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 33, 'https://user-images.githubusercontent.com/100201504/208111596-77115f52-f86f-4a38-be44-bf933366ec21.png');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32, 'https://user-images.githubusercontent.com/100201504/202725122-3e85111a-c5a0-4f6f-bd7c-0be6c74ce42e.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 21, 'https://user-images.githubusercontent.com/100201504/202725138-01734cf9-9c3c-43f7-89d2-ba18534a8feb.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 30, 'https://user-images.githubusercontent.com/100201504/202725158-7aa42866-0b00-4384-bac8-0e5544e2523f.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 25, 'https://user-images.githubusercontent.com/100201504/202725224-2703c18b-1371-48e1-8e06-96ff34401599.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 25, 'https://user-images.githubusercontent.com/100201504/202725208-f896676c-9bac-46a4-965a-d2ad230148de.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 23, 'https://user-images.githubusercontent.com/100201504/202724912-f37dcd9c-4675-482e-9094-8bce9e19be36.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 24, 'https://user-images.githubusercontent.com/100201504/202724924-3d1e5496-6296-4dd1-8617-e840d53fb9ad.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32, 'https://user-images.githubusercontent.com/100201504/202725143-d6eeeb56-5cc3-42b5-b457-baefcc99ea02.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202725069-baa75a0f-0977-4aa5-9e20-0b56cf06572b.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 40, 'https://user-images.githubusercontent.com/100201504/202725185-6bd4f9e9-64d1-43d6-a3ae-b71ccf70ff26.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 51, 'https://user-images.githubusercontent.com/100201504/202725045-1285f278-916d-436a-bf73-cb7787135a68.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 62, 'https://user-images.githubusercontent.com/100201504/202725058-c0ca7dac-bd75-406a-8966-6f00282b42fb.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35, 'https://user-images.githubusercontent.com/100201504/202725212-6bef5836-f646-4bea-b72e-a45390172aae.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 26, 'https://user-images.githubusercontent.com/100201504/202725171-70bcf6b3-3baf-4680-87ed-b97301b00c19.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 42, 'https://user-images.githubusercontent.com/100201504/202725270-f2265315-3059-430e-a6d3-dfb45222b7d5.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35, 'https://user-images.githubusercontent.com/100201504/202725179-ff47b61c-70a8-4e27-bd55-9fb746961742.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 29, 'https://user-images.githubusercontent.com/100201504/202725241-86147fb5-c84d-4075-9b4e-17b78c8b0f73.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 29, 'https://user-images.githubusercontent.com/100201504/202725247-2ada9101-8bee-45fc-b37f-1badd90ad122.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 43, 'https://user-images.githubusercontent.com/100201504/202725253-d216e45a-1257-4584-b5f4-9f9338ab8cfc.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 25, 'https://user-images.githubusercontent.com/100201504/202725252-5b29bb9f-08a6-4cc4-965f-be787a120cba.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202724927-8a8ab111-bf25-4c05-9902-9fdc5b7f175b.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 43, 'https://user-images.githubusercontent.com/100201504/202724933-bf878630-aab8-4bea-874b-be5c5c1e7e00.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 42, 'https://user-images.githubusercontent.com/100201504/202724940-59b5bf97-a853-4046-98d9-b2c78180a21b.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 15, 'https://user-images.githubusercontent.com/100201504/202724941-f48dec40-b6d8-45b7-88ee-7eaafb092279.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 33, 'https://user-images.githubusercontent.com/100201504/202724944-3ce14188-e044-422b-ba8c-06692b09ae4f.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18, 'https://user-images.githubusercontent.com/100201504/202724947-556d44df-56b5-4f76-b713-da3e7d1480fa.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 38, 'https://user-images.githubusercontent.com/100201504/202724950-37431097-f23f-4e89-8e86-f1ba28f99d13.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 53, 'https://user-images.githubusercontent.com/100201504/202724954-36acaca8-8327-463b-8585-157b785781fc.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 43, 'https://user-images.githubusercontent.com/100201504/202724961-38c67b75-1965-4362-9515-0521adaad61a.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 27, 'https://user-images.githubusercontent.com/100201504/202724964-236bcf41-07be-4eb9-8a29-13f858eab105.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 39, 'https://user-images.githubusercontent.com/100201504/202724911-6f8f920b-6596-4187-aa82-d1386b72f562.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 48, 'https://user-images.githubusercontent.com/100201504/202724903-1cac9bf5-0d65-45a9-ae01-0cde2bf4fc65.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18, 'https://user-images.githubusercontent.com/100201504/202724967-2a714ac1-21b0-493c-adda-1cceb14709b1.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 29, 'https://user-images.githubusercontent.com/100201504/202724972-bc6830c0-3630-4ab4-a311-bbabc6321948.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 31, 'https://user-images.githubusercontent.com/100201504/202724978-665c8281-64c6-427b-a7aa-9d07ce382c51.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 43, 'https://user-images.githubusercontent.com/100201504/202724981-70fb61e2-c855-4286-b2c2-9d9d08860332.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202724991-d9dbc88b-a66e-43fd-83da-da0bca1e80b8.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32, 'https://user-images.githubusercontent.com/100201504/202724995-e63881e3-8585-407c-be99-b92d5168378c.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 57, 'https://user-images.githubusercontent.com/100201504/202725000-9633228b-e9f7-4fca-ae56-3afc3016c9f3.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 50, 'https://user-images.githubusercontent.com/100201504/202725005-73e4f3dd-011e-4583-9729-f320a0092eb6.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35, 'https://user-images.githubusercontent.com/100201504/202725011-ae150e81-c1b0-4c7f-8114-f741ce68b6cf.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 15, 'https://user-images.githubusercontent.com/100201504/202725020-afa3899b-55ff-4123-bfff-7bd2c3b8028d.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 33, 'https://user-images.githubusercontent.com/100201504/202725023-2e04a8d3-360d-4c33-883c-a2d6b4bc290b.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 19, 'https://user-images.githubusercontent.com/100201504/202725027-229d0d0f-2ac0-4893-9b9c-e93435981c28.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 20, 'https://user-images.githubusercontent.com/100201504/202725032-5c3c057e-d468-4619-9256-03779b9562af.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 53, 'https://user-images.githubusercontent.com/100201504/202725036-1c6a1c71-2a20-40da-acfd-07774005bdc7.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 62, 'https://user-images.githubusercontent.com/100201504/202725039-c9afa14a-17d3-4692-a53b-db5627417a7d.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 24, 'https://user-images.githubusercontent.com/100201504/202725053-da49dd76-7513-44ea-864c-0aeecc318bae.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 39, 'https://user-images.githubusercontent.com/100201504/202725061-dde3f09b-2b36-4bef-8ac1-3b5e603fd3d1.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 42, 'https://user-images.githubusercontent.com/100201504/202725075-e9badfc2-d8d0-41a9-9ebd-180f69dd1f16.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 23, 'https://user-images.githubusercontent.com/100201504/202725078-6eb7b945-2c60-47ed-80f2-dcb7ac0fd506.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 41, 'https://user-images.githubusercontent.com/100201504/202725081-76c1ffd2-ce95-4619-9c17-9f70d810b93e.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202725090-b0a16098-cc27-4b71-afbb-f9e4d74d4556.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 27, 'https://user-images.githubusercontent.com/100201504/202725095-4f644a8c-b4d1-48b1-9902-46726dbfb675.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 38, 'https://user-images.githubusercontent.com/100201504/202725096-3972b91d-ee5b-477c-a208-0f9fcfe413af.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 34, 'https://user-images.githubusercontent.com/100201504/202725104-097814bd-c661-4d63-a7eb-08b868eac94e.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18, 'https://user-images.githubusercontent.com/100201504/202725108-5c459d92-78d1-422f-b2fe-9edb0d8ab794.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 26, 'https://user-images.githubusercontent.com/100201504/202725112-329618f1-261d-4a85-a8e4-687e44c60e1a.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32, 'https://user-images.githubusercontent.com/100201504/202725114-af5d3684-1ba3-4ac5-be3c-ecec63b5f889.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 21, 'https://user-images.githubusercontent.com/100201504/202725117-08e7fcc3-8d08-4c6a-9f8d-72b2112f18b0.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 45, 'https://user-images.githubusercontent.com/100201504/202725126-4fc83335-0a34-4f01-8241-a6092c33b265.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 19, 'https://user-images.githubusercontent.com/100201504/202725128-ec847c45-66c7-482b-be88-5e4e3a46fa12.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 14, 'https://user-images.githubusercontent.com/100201504/202725145-a4e300b5-45df-4745-83c6-a417585f32a2.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 53, 'https://user-images.githubusercontent.com/100201504/202725148-290cca32-02cf-4f35-9255-e7f23aa2bf81.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 24, 'https://user-images.githubusercontent.com/100201504/202725163-280e314f-3768-4805-8f3b-8f1e2a778f60.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202725174-e69fb43d-0c41-4c81-b9f5-e475e0ec3248.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 25, 'https://user-images.githubusercontent.com/100201504/202725191-f1ea93b4-f04d-4b08-aa0e-7b583a905ef1.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18, 'https://user-images.githubusercontent.com/100201504/202725196-818c54e4-b4c2-4ce2-89eb-6ceac8639e6d.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 64, 'https://user-images.githubusercontent.com/100201504/202725197-ba07103e-d133-4a4e-8d93-c2b3a6bf6279.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35, 'https://user-images.githubusercontent.com/100201504/202725201-b8a03b3d-c10d-4290-b914-8f1a4d65171d.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 27, 'https://user-images.githubusercontent.com/100201504/202725217-8cbbac5b-c581-4a9a-b5b9-798f094c4faa.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 34, 'https://user-images.githubusercontent.com/100201504/202725220-14d914f4-b0d8-4e1f-a058-bf5eaad22138.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 17, 'https://user-images.githubusercontent.com/100201504/202725226-4b8b83ec-1d8d-47aa-8c9a-cf72de750879.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 52, 'https://user-images.githubusercontent.com/100201504/202725227-680e1a6a-d167-4f7e-82f3-b710a9a28b0e.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 53, 'https://user-images.githubusercontent.com/100201504/202725237-9b25cfd8-2240-49dd-af83-042b3150c142.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 34, 'https://user-images.githubusercontent.com/100201504/202725244-68fa5c7b-176a-45c1-b564-a5c8e1e87b84.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 12, 'https://user-images.githubusercontent.com/100201504/202725254-3489047d-8b6c-4bdd-b8f7-08ebd3a7a20b.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 'https://user-images.githubusercontent.com/100201504/202725258-e1a7f976-da1b-4cfd-811d-7b1ec690c080.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 33, 'https://user-images.githubusercontent.com/100201504/202725261-2e971f6d-b617-4120-899a-67644169a8fb.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35, 'https://user-images.githubusercontent.com/100201504/202725264-1864364d-9aa8-4f7b-9555-6c46115658c5.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 45, 'https://user-images.githubusercontent.com/100201504/202725266-c021d790-9c35-4de3-97ed-1e8aaf6446cc.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32, 'https://user-images.githubusercontent.com/100201504/202725275-1723f394-9db4-4386-a383-13f299622a15.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 37, 'https://user-images.githubusercontent.com/100201504/202724921-48759e4b-dcb4-4391-a03f-e4d511763e35.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 40, 'https://user-images.githubusercontent.com/100201504/202724993-d2024a1a-9654-4449-b3e8-dd68fbe731a6.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 30, 'https://user-images.githubusercontent.com/100201504/202725043-18c09960-3808-4985-a59f-120f73df2246.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 42, 'https://user-images.githubusercontent.com/100201504/202724983-3c6cd470-dcea-4419-b154-013cc3aa3194.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 17, 'https://user-images.githubusercontent.com/100201504/202725066-fb080034-1ecb-4aa1-821c-6421be885529.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 23, 'https://user-images.githubusercontent.com/100201504/202725133-08c426e3-d43e-4a43-a619-7ad8006e8068.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 45, 'https://user-images.githubusercontent.com/100201504/202725018-2e139fb3-c249-4dfa-830d-bcd151414fc0.jpg');
insert into images (user_id, status, short_description, long_description, price, url)
values (1, 'approved', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Duis eget arcu eu felis luctus vulputate quis in massa. Praesent tempor quam et elit efficitur, ac consequat nulla sollicitudin. Maecenas urna massa, ultrices non aliquet et, blandit vitae est. Aenean rhoncus justo vel placerat aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 26, 'https://user-images.githubusercontent.com/100201504/202725064-433c2f3f-40b7-476e-b7e8-6a3124a04c15.jpg');


insert into ratings (user_id, image_id, rating, review, status)
values (2, 1, 5, 'Sed in neque neque. Ut eget dui quis urna pulvinar suscipit sit amet at tellus. Donec sed sodales eros, nec dictum odio. Maecenas vel vulputate leo, non semper risus. Ut egestas fringilla diam a tempor. Etiam malesuada, velit a laoreet consequat, urna felis laoreet erat, vel volutpat velit sem non justo. Vivamus id aliquet ex, sed fermentum nulla. Curabitur ut enim augue. Suspendisse pharetra pulvinar consequat. Nam ut tincidunt dui.', 'new');
insert into ratings (user_id, image_id, rating, review, status)
values (2, 2, 2, 'Sed in neque neque. Ut eget dui quis urna pulvinar suscipit sit amet at tellus. Donec sed sodales eros, nec dictum odio. Maecenas vel vulputate leo, non semper risus. Ut egestas fringilla diam a tempor. Etiam malesuada, velit a laoreet consequat, urna felis laoreet erat, vel volutpat velit sem non justo. Vivamus id aliquet ex, sed fermentum nulla. Curabitur ut enim augue. Suspendisse pharetra pulvinar consequat. Nam ut tincidunt dui.', 'new');


insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 1, 'completed', false, 30);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 2, 'completed', false, 50);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 3, 'cancelled', false, 40);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 4, 'cancelled', false, 25);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 5, 'pending', false, 30);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 6, 'pending', false, 35);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 7, 'awaiting_payment', false, 40);
insert into orders (user_id, image_id, status, with_discount, amount)
values (2, 8, 'awaiting_payment', false, 45);